version: '3'

services:
    redis:
      image: redis
      networks:
      - lto

    anchor:
      container_name: anchor
      image: legalthings/anchor
      environment:
      - LTO_API_KEY=<a secret to use the api>
      - NODE_ENV=lto
      networks:
      - lto
      depends_on:
      - redis
      - public-node

    public-node:
      container_name: public-node
      image: legalthings/public-node
      environment:
      - ENABLE_REST_API=true
      - LTO_WALLET_SEED=<seed of your wallet>
      - LTO_API_KEY=<a secret to use the api>
      networks:
      - lto

    rabbitmq:
      image: legalthings/rabbitmq
      networks:
      - lto

    mongo:
      image: "mongo:3"
      networks:
      - lto

    lto-webserver:
      container_name: webserver
      image: legalthings/webserver
      environment:
       - NODE_ENV=production
      ports:
        - "3000:80"
      networks:
        - lto

    legalflow:
      container_name: legalflow
      image: legalthings/legalflow
      environment:
       - APPLICATION_ENV=lto
       - phpmemory_limit=512M
      networks:
        - lto
      depends_on:
       - mongo

    legalevents:
      container_name: legalevents
      image: legalthings/legalevents
      environment:
      - APPLICATION_ENV=lto
      - phpmemory_limit=512M
      networks:
      - lto
      depends_on:
      - mongo

    event-queuer:
      container_name: event-queuer
      image: legalthings/event-dispatcher
      environment:
      - NODE_ENV=lto
      networks:
      - lto
      depends_on:
      - mongo
      - rabbitmq

networks:
  lto:
    driver: bridge
