version: '3'

services:
  rabbitmq:
    image: legalthings/rabbitmq
    networks:
      - lto

  mongo:
    image: "mongo:3"
    ports:
      - 27747:27017
    networks:
      - lto

  api-gateway:
    container_name: api-gateway
    image: legalthings/api-gateway:v0.1.7
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    networks:
      - lto

  legalflow:
    container_name: legalflow
    image: legalthings/workflow-engine:v0.1.3
    environment:
      - APPLICATION_ENV=docker.dev-queue
      - phpmemory_limit=512M
    volumes:
      - ./workflow-engine-config:/app/config/local
    networks:
      - lto
    depends_on:
      - mongo

  legalevents:
    container_name: legalevents
    image: legalthings/event-chain:v0.1.2
    environment:
      - APPLICATION_ENV=docker.dev-queue
      - phpmemory_limit=512M
    networks:
      - lto
    depends_on:
      - mongo

  event-queuer:
    container_name: event-queuer
    image: legalthings/event-dispatcher:v0.1.2
    environment:
      - NODE_ENV=lto
    networks:
      - lto
    depends_on:
      - mongo
      - rabbitmq

  event-dispatcher:
    container_name: event-dispatcher
    image: legalthings/event-dispatcher:v0.1.2
    environment:
      - NODE_ENV=lto
    networks:
      - lto
    depends_on:
      - mongo
      - rabbitmq

networks:
  lto:
    driver: bridge
